SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE classroom;
TRUNCATE TABLE school;
TRUNCATE TABLE student;
TRUNCATE TABLE student_grade_test;
TRUNCATE TABLE bimester;
TRUNCATE TABLE test;
TRUNCATE TABLE teacher;
TRUNCATE TABLE discipline;
TRUNCATE TABLE teacher_disciplines_discipline;
TRUNCATE TABLE year;

SET FOREIGN_KEY_CHECKS=1;