SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE category;
TRUNCATE TABLE person_category;
TRUNCATE TABLE person;
TRUNCATE TABLE activity;
TRUNCATE TABLE activity_type;
TRUNCATE TABLE address;
TRUNCATE TABLE class;
TRUNCATE TABLE class_student;
TRUNCATE TABLE class_type;
TRUNCATE TABLE contract;
TRUNCATE TABLE discipline;
TRUNCATE TABLE employment_contract;
TRUNCATE TABLE final_grade;
TRUNCATE TABLE final_grade_student_activity;
TRUNCATE TABLE occupation;
TRUNCATE TABLE period;
TRUNCATE TABLE phone;
TRUNCATE TABLE responsabile;
TRUNCATE TABLE school;
TRUNCATE TABLE student;
TRUNCATE TABLE student_activity;
TRUNCATE TABLE supervisor;
TRUNCATE TABLE teacher;
TRUNCATE TABLE teacher_class;
TRUNCATE TABLE teacher_discipline; 

TRUNCATE TABLE year;
SET FOREIGN_KEY_CHECKS=1;